---
- name: Ensure hostname doesn't resolve to localhost
  replace:
    path: /etc/hosts
    regexp: '^127.0.0.1\t{{ FQDN }}\t{{ HOSTNAME }}'
    replace: '{{ IP_ADDRESS }}\t{{ FQDN }}\t{{ HOSTNAME }}'
    backup: no
  become: true

- name: Install FreeIPA server
  package: name=freeipa-server
  become: true

- name: Is FreeIPA already configured?
  stat: path=/var/log/ipaserver-install.log
  register: install_log

- name: Configure FreeIPA server
  command: ipa-server-install --unattended --admin-password={{ ADMIN_PASSWORD }} --ds-password={{ ADMIN_PASSWORD }} --hostname={{ FQDN }} --domain={{ DOMAIN }} --realm={{ DOMAIN|upper }}
  when: not install_log.stat.exists
  become: true

- name: Ensure admin config / auth to Kerberos realm
  shell: echo '{{ ADMIN_PASSWORD }}' | kinit admin
  become: true
